= Εφαρμοσμένα Μαθηματικά
v0.1
:sectanchors:
:toc-title: Περιεχόμενα
:toc: left
:stem: latexmath
:eqnums: asm
:blank: pass:[ +]
:warning-caption: 🔥
:tip-caption: 💡

== Συντομογραφίες
[cols="1,1"]
|===
|s2p5  		|slide 2, page 5
|Δ.Ε.		|Διαφορική Εξίσωση
|Σ.Δ.Ε.		|Συνήθης Διαφορική Εξίσωση
|Μ.Δ.Ε.		|Μερική Διαφορική Εξίσωση
|Π.Α.Τ.		|Πρόβλημα Αρχικών Τιμών
|===

== Βασικές έννοιες

Διαφορική εξίσωση::
Μια εξίσωση που περιέχει μια άγνωστη συνάρτηση και παραγώγους της.

[svgbob]
....



                     μίας μεταβλητής
                    .-----------------> συνήθης Δ.Ε.
                   /
άγνωστη συνάρτηση o
                   \
                    `-----------------> μερική Δ.E.
                     πολλών μεταβλητών




....

Tάξη::
pass:[...] μιας Δ.Ε. είναι η τάξη της ανώτερης παραγώγου της άγνωστης συνάρτησης.

Γενική μορφή::
+
[#eq-1,reftext="(1)"]
[stem]
++++
\begin{equation}
F(x,y,y',...,y^{(n)})=0
\end{equation}
++++

+
όπου stem:[y=y(x)].

Κανονική μορφή::
[stem]
++++
\begin{equation}
y^{(n)}=G(x,y,y',...,y^{(n-1)}) 
\end{equation}
++++

=== Γραμμικές Διαφορικές Εξισώσεις
Γενική μορφή γραμμικής Δ.Ε.::
[#eq-3, reftext=(3)]
[stem]
++++
\begin{equation}
a_n(x)y^{(n)}(x) + a_{(n-1)}(x)y^{(n-1)}(x) + ... + a_0(x)y(x) = f(x)
\end{equation}
++++

Συντελεστές::
pass:[...] της γραμμικής Δ.Ε. ονομάζονται οι συναρτήσεις stem:[a_i(x)].

Ομογενής::
stem:[f(x)=0] (στην <<eq-3>>)

Σταθερών συντελεστών::
Οι συντελεστές είναι σταθερές συναρτήσεις.

Πρόβλημα Αρχικών Τιμών::
Σου δίνει αρχικές τιμές και πρέπει να βρεις τη λύση χρησιμοποιώντας αυτές τις
τιμές.
+
Δες <<μερική-λύση>>

{blank}

WARNING: Ελέγχουμε για ομοιογένεια και σταθερούς συντελεστές μόνο αν η Δ.Ε. 
είναι γραμμική.

{blank}

.Είδη διαφορικών εξισώσεων
[example]
====
[cols="1,1"]
|===
|stem:[y'=x]									| Πρώτης τάξης, γραμμική, μη ομεγενής, με σταθερούς συντελεστές
|stem:[(y'')^4 + 3y(y')^5 + y^3y' = 3x]			| Δεύτερης τάξης, μη γραμμική
|===
====

=== Λύσεις Διαφορικών Εξισώσεων

Κλασσική λύση::
Μια συνάρτηση stem:[y=y(x)] η οποία επαληθεύει την <<eq-1>>.

Γενική λύση::
+
[stem]
++++
\begin{equation}
y = y(x) = φ(x,c_1,...,c_n)
\end{equation}
++++

+
όπου stem:[c_1, ..., c_n \in \mathbb{R}]

.Γενική λύση διαφορικής εξίσωσης
[example]
====
Η διαφορική εξίσωση. 

[stem]
++++
y''-y'-2y=0
++++

έχει ως γενική λύση την 
[stem]
++++
y(x)=c_1e^{-x} + c_2e^{2x}, c_1, c_2 \in \mathbb{R}
++++
====

[#μερική-λύση,reftext="Μερική ή ειδική λύση"]
Μερική ή ειδική λύση::
Αν στην γενική λύση βάλουμε συγκεκριμένα c.

[TIP]
====
Aν μας δίνει αρχικές τιμές (Π.Α.Τ.), τότε θα βρούμε τα συγκεκριμένα c στη 
γενική λύση ή στο γενικό ολοκλήρωμα και άρα θα πάρουμε μία μερική λύση.
====

.Π.Α.Τ.
[example]
====
s1p4
====

Γενικό ολοκλήρωμα::
+
[stem]
++++
\begin{equation}
G(x,y,c_1,...,c_n)=0
\end{equation}
++++
+
* Σε αντίθεση με τη γενική λύση, το γενικό ολοκλήρωμα είναι συνάρτηση και του y.
** Περιλαμβάνει δηλαδή τη y, υπό πεπλεγμένη μορφή.
* Αφήνουμε την Δ.Ε. ως γενικό ολοκλήρωμα όταν δεν μπορούμε να λύσουμε ως προς y.

.Γενικό ολοκλήρωμα διαφορικής εξίσωσης
[example]
====
s1p3
====
