= Εφαρμοσμένα Μαθηματικά
v0.1
:sectanchors:
:toc-title: Περιεχόμενα
:toc: left
:toclevels: 4
:stem: latexmath
:eqnums: asm
:blank: pass:[ +]
:warning-caption: 🔥
:tip-caption: 💡

== Συντομογραφίες
[cols="1,1"]
|===
|Δ.Ε.		|Διαφορική Εξίσωση
|Σ.Δ.Ε.		|Συνήθης Διαφορική Εξίσωση
|Μ.Δ.Ε.		|Μερική Διαφορική Εξίσωση
|Π.Α.Τ.		|Πρόβλημα Αρχικών Τιμών
|===

== Παραπομπές
* Εφαρμοσμένα Μαθηματικά, Νικόλαος Τσίτσας

== Διαφορικές Εξισώσεις
=== Βασικές έννοιες

Διαφορική εξίσωση::
Μια εξίσωση που περιέχει μια άγνωστη συνάρτηση και παραγώγους της.

[svgbob]
....



                     μίας μεταβλητής
                    .-----------------> συνήθης Δ.Ε.
                   /
άγνωστη συνάρτηση o
                   \
                    `-----------------> μερική Δ.E.
                     πολλών μεταβλητών




....

Tάξη::
pass:[...] μιας Δ.Ε. είναι η τάξη της ανώτερης παραγώγου της άγνωστης συνάρτησης.

Γενική μορφή::
+
[#eq-1,reftext="(1)"]
[stem]
++++
\begin{equation}
F(x,y,y',...,y^{(n)})=0
\end{equation}
++++

+
όπου stem:[y=y(x)].

Κανονική μορφή::
[stem]
++++
\begin{equation}
y^{(n)}=G(x,y,y',...,y^{(n-1)}) 
\end{equation}
++++

Πρόβλημα Αρχικών Τιμών::
Σου δίνει αρχικές τιμές και πρέπει να βρεις τη <<μερική-λύση>> χρησιμοποιώντας αυτές τις
τιμές.

==== Γραμμικές Διαφορικές Εξισώσεις
Γενική μορφή γραμμικής Δ.Ε.::
[#eq-3, reftext=(3)]
[stem]
++++
\begin{equation}
a_n(x)y^{(n)}(x) + a_{(n-1)}(x)y^{(n-1)}(x) + ... + a_0(x)y(x) = f(x)
\end{equation}
++++

Συντελεστές::
pass:[...] της γραμμικής Δ.Ε. ονομάζονται οι συναρτήσεις stem:[a_i(x)].

Ομογενής::
stem:[f(x)=0] (στην <<eq-3>>)

Σταθερών συντελεστών::
Οι συντελεστές είναι σταθερές συναρτήσεις.


{blank}

WARNING: Ελέγχουμε για ομοιογένεια και σταθερούς συντελεστές μόνο αν η Δ.Ε. 
είναι γραμμική.

{blank}

.Είδη διαφορικών εξισώσεων
[example]
====
[cols="1,1"]
|===
|stem:[y'=x]									| Πρώτης τάξης, γραμμική, μη ομεγενής, με σταθερούς συντελεστές
|stem:[(y'')^4 + 3y(y')^5 + y^3y' = 3x]			| Δεύτερης τάξης, μη γραμμική
|===
====

==== Λύσεις Διαφορικών Εξισώσεων

Κλασσική λύση::
Μια συνάρτηση stem:[y=y(x)] η οποία επαληθεύει την <<eq-1>>.

Γενική λύση::
+
[stem]
++++
\begin{equation}
y = y(x) = φ(x,c_1,...,c_n)
\end{equation}
++++

+
όπου stem:[c_1, ..., c_n \in \mathbb{R}]

.Γενική λύση διαφορικής εξίσωσης
[example]
====
Η διαφορική εξίσωση. 

[stem]
++++
y''-y'-2y=0
++++

έχει ως γενική λύση την 
[stem]
++++
y(x)=c_1e^{-x} + c_2e^{2x}, c_1, c_2 \in \mathbb{R}
++++
====

[#μερική-λύση,reftext="μερική λύση"]
Μερική ή ειδική λύση::
Αν στην γενική λύση βάλουμε συγκεκριμένα c.

[TIP]
====
Aν μας δίνει αρχικές τιμές (Π.Α.Τ.), τότε θα βρούμε τα συγκεκριμένα c στη 
γενική λύση ή στο γενικό ολοκλήρωμα και άρα θα πάρουμε μία μερική λύση.
====

.Π.Α.Τ.
[example]
====
p18
====

Γενικό ολοκλήρωμα::
+
[stem]
++++
\begin{equation}
G(x,y,c_1,...,c_n)=0
\end{equation}
++++
+
* Σε αντίθεση με τη γενική λύση, το γενικό ολοκλήρωμα είναι συνάρτηση και του y.
** Περιλαμβάνει δηλαδή τη y, υπό πεπλεγμένη μορφή.
* Αφήνουμε την Δ.Ε. ως γενικό ολοκλήρωμα όταν δεν μπορούμε να λύσουμε ως προς y.

.Γενικό ολοκλήρωμα διαφορικής εξίσωσης
[example]
====
p17
====

=== Πρώτης Τάξης
Δ.E. Πρώτης Τάξης::
[stem]
++++
\begin{equation}
y'(x) = f(x,y(x))
\end{equation}
++++

==== Χωριζομένων μεταβλητών
Δ.Ε. Χωριζομένων μεταβλητών ή διαχωρίσιμη Δ.Ε.::

[stem]
++++
\begin{equation}
y'=g(x)h(y)
\end{equation}
++++

*Μεθοδολογία*

. Λύσε την εξίσωση stem:[h(y)=0]
** Οι λύσεις αυτής της εξίσωσης:
*** Είναι σταθερές (stem:[y=ρ])
*** Αποτελούν λύσεις της Δ.Ε.
*** Ονομάζονται *ιδιάζουσες*.
. Για stem:[h(y) \neq 0]
** Διαίρεσε και τα δύο μέλη με την stem:[h(y)]
** Ολοκλήρωσε ως προς stem:[x]
*** Ισχύει stem:[y'=\frac{dy}{dx}]

.Π.Α.Τ.
[WARNING] 
====
Μας δίνεται αρχική τιμή stem:[y(x_0)=y_0]

* Οι ιδιάζουσες λύσεις stem:[y=ρ] δεν αποτελούν λύσεις του Π.Α.Τ. αν δεν είναι ίσες με τις αρχικές τιμές που μας δίνονται.
* Η λύση ενός Π.Α.Τ. πρέπει να ορίζεται σε ένα διάστημα που περιέχει το αρχικό σημείο stem:[x_0].
====
